### ISSUE TITLE
`v2.0.0` causes display resolution issues

### ISSUE THREAD

**Issue by mpustovoi** [Kira-NT/cubes-without-borders#17]
After installing your mod in my custom modpack for version 1.21, when I start the game, my PC interface size greatly increases for a few seconds.
A black screen appears first. Then my screen resolution gets to about 800×600 or so (all fonts and windows become huge) until the main Minecraft menu appears. After that, everything comes back to normal. And this happens every time you start it.
With other Minecraft versions, I didn't have such a problem. Perhaps the presence of the [fullscreeNO](https://modrinth.com/mod/fullscreeno) mod helped. However, it's not yet available for 1.21. I force-installed it, but it doesn't seem to work.
[Logs](https://mclo.gs/uMGBRrL). No crash-report.

**Comment by Kira-NT** [comment]
So, GLFW doesn't allow you to choose the starting location of a window you create. This is why, previously with CWB installed, you could see Minecraft starting as a small window and only after a few seconds resizing to its full borderless fullscreen glory. In `v2.0.0`, I decided to circumvent that by creating a "proper" fullscreen window and then immediately turning it into a borderless fullscreen one, to squeeze a smoother startup experience out of this whole ordeal.

However, this also means that a custom video mode may be temporarily applied during that transition, if it is set at all, of course. This shouldn't be the case, honestly, and I'm going to tweak it in a future version. In the meantime, to fix the problem on your end, you need to ensure that there is no custom fullscreen resolution set. To do that, go to the video settings *(if you have Sodium installed, press <kbd>Shift</kbd> + <kbd>P</kbd> to jump from Jelly's settings screen to the original one)*, and bring the "Fullscreen Resolution" slider all the way to the left until it says "Current," like so:

![Example](https://github.com/Kir-Antipov/cubes-without-borders/assets/40232067/b8de475c-caae-4603-a328-63aa8f535eeb)

Alternatively, you can open the `.minecraft/options.txt` file, locate the `fullscreenResolution` property, and simply delete it. It should look something like this in your case:

```properties
fullscreenResolution:800x600@60:24
```

Without a custom fullscreen resolution set, the game should use your current one and stop messing up your desktop!

**Comment by mpustovoi** [comment]
Unfortunately, this temporary solution didn't help. In the in-game settings, "Fullscreen Resolution" has already been set to "Current". However, in `options.txt` there was no `fullscreenResolution` line at all.
I've done the steps you described, but `fullscreenResolution` never appeared in the settings, and the next time I started the computer interface was attacked again.
I'll try again later, saving a different screen resolution first.

**Comment by Kira-NT** [comment]
> "Fullscreen Resolution" has already been set to "Current". However, in `options.txt` there was no `fullscreenResolution` line at all.

They are the same thing, so if `fullscreenResolution` is already unset, "Fullscreen Resolution" will display "Current" in the settings.

Do you start the game with the `--fullscreenWidth` and `--fullscreenHeight` flags by any chance? These are an alternative way of setting a custom fullscreen resolution at startup.

If not, this could mean there is something wrong with your current video mode (detection?) in general. In that case, try setting it up manually via the "Fullscreen Resolution" slider.

**Comment by mpustovoi** [comment]
> Do you start the game with the `--fullscreenWidth` and `--fullscreenHeight` flags by any chance? These are an alternative way of setting a custom fullscreen resolution at startup.

I start the game in Modrinth App with default settings for Fabric 1.21. I don't even know how to write these flags here.

> If not, this could mean there is something wrong with your current video mode (detection?) in general. In that case, try setting it up manually via the "Fullscreen Resolution" slider.

I don't get about what kind of slider it is. In the settings via `Shift` + `P` there are only "Current" (which is set for me but it doesn't help) and the values "X×Y" from "640×480` to "3840×2160".

**Comment by Julienraptor01** [comment]
> > "Fullscreen Resolution" has already been set to "Current". However, in `options.txt` there was no `fullscreenResolution` line at all.
> 
> They are the same thing, so if `fullscreenResolution` is already unset, "Fullscreen Resolution" will display "Current" in the settings.
> 
> Do you start the game with the `--fullscreenWidth` and `--fullscreenHeight` flags by any chance? These are an alternative way of setting a custom fullscreen resolution at startup.
> 
> If not, this could mean there is something wrong with your current video mode (detection?) in general. In that case, try setting it up manually via the "Fullscreen Resolution" slider.

many custom launchers do start with these flags without telling the user i think
![image](https://github.com/Kir-Antipov/cubes-without-borders/assets/49841713/bff3ad6e-961f-457b-b177-79ff5438a8f4)
also i got the issue too and for me it was worse than just wrong res
it completely broke the fact that i have multiple displays disabling one temporarily and broke other apps than MC permanently until restarted alongside the effect of causing flashes

**Comment by mpustovoi** [comment]
I guess I have to disable the mod because there's no solutions for now.

**Comment by Julienraptor01** [comment]
> I guess I have to disable the mod because there's no solutions for now.

you can rollback to 1.0.0 for now if it's supported on your MC version

**Comment by mpustovoi** [comment]
> you can rollback to 1.0.0 for now if it's supported on your MC version

For my 1.21 modpack, unfortunately, I can't.

**Comment by Kira-NT** [comment]
Sooooo, I re-read MC's code, and it's just wrong:

```java
this.windowedWidth = this.width = settings.width > 0 ? settings.width : 1;
this.windowedHeight = this.height = settings.height > 0 ? settings.height : 1;

// ...

this.handle = GLFW.glfwCreateWindow(this.width, this.height, title, this.fullscreen && monitor != null ? monitor.getHandle() : 0L, 0L);
```

The `width` and `height` for fullscreen windows are treated as the desired resolution, i.e., `854x480` in our case, which is the default windowed dimensions for Minecraft. Regular fullscreen doesn't mess up your resolution because it quickly patches it afterward *(instead of setting the right one upfront)*, while I didn't expect such a blow from the vanilla logic and didn't account for it.

Give me 5 minutes, and this will be fixed, as currently, it's broken for all versions. Gosh darn it.

**Comment by Kira-NT** [comment]
It should be fixed now! If some of you affected folks could quickly test this on your machines *(I cannot reproduce the problem on mine, even though I can clearly see the root of the problem)* before I publish a release, that would be greatly appreciated!

You can grab a pre-built version of the patched mod from here:

 - 1.19.3-1.19-4: https://github.com/Kir-Antipov/cubes-without-borders/actions/runs/9667358054
 - 1.20.x: https://github.com/Kir-Antipov/cubes-without-borders/actions/runs/9667369158
 - 1.21: https://github.com/Kir-Antipov/cubes-without-borders/actions/runs/9667372736

**Comment by Julienraptor01** [comment]
> It should be fixed now! If some of you affected folks could quickly test this on your machines _(I cannot reproduce the problem on mine, even though I can clearly see the root of the problem)_ before I publish a release, that would be greatly appreciated!
> 
> You can grab a pre-built version of the patched mod from here:
> 
>     * 1.19.3-1.19-4: https://github.com/Kir-Antipov/cubes-without-borders/actions/runs/9667358054
> 
>     * 1.20.x: https://github.com/Kir-Antipov/cubes-without-borders/actions/runs/9667369158
> 
>     * 1.21: https://github.com/Kir-Antipov/cubes-without-borders/actions/runs/9667372736

so i just tested it and noticed a few bad things
- when mc launch it now steal your cursor in the middle on it which is extremely annoying on multi-monitor setup as you may be doing smth else
which when i try to use the 1.1.0 or 1.0.0 doesn't happen
- when mc launch during the time where the window is black with nothing on it even if you alt-tab to another window to unfocus it and focus a window behind, it does focus it but stay behind so you basically can't use the monitor MC is displaying on
which when i try to use the 1.1.0 or 1.0.0 doesn't happen

(note : i am testing this with other fabric mods such as sodium, which i know has workarounds that touch window creation or smth to prevent an issue so maybe it could be adding up to the issue)

**Comment by mpustovoi** [comment]
> It should be fixed now! If some of you affected folks could quickly test this on your machines _(I cannot reproduce the problem on mine, even though I can clearly see the root of the problem)_ before I publish a release, that would be greatly appreciated!

The problem with messing up the screen resolution has gone, but when a black game loading screen appears (and then a white one), I also lose control of the computer.
I don't have multiple screen, but, I still can't leave the MC to run in the background, because it will take the focus on itself and it also says that the app doesn't respond for 10-15 seconds until the main menu appears.

**Comment by Kira-NT** [comment]
Sigh, ok, I can turn off the fullscreen startup entirely for the time being. However, it's going to degrade the experience for folks who play Minecraft on a secondary monitor, as GLFW creates non-fullscreen windows only on the primary one.

**Comment by Julienraptor01** [comment]
> Sigh, ok, I can turn off the fullscreen startup entirely for the time being. However, it's going to degrade the experience for folks who play Minecraft on a secondary monitor, as GLFW creates non-fullscreen windows only on the primary one.

Can't you just create it on the primary monitor and move it to the right monitor after it's been created ?

**Comment by Julienraptor01** [comment]
idk how borderless mining do it, but when i use borderless mining on 1.19.2 i can easily set it to use monitor x and it does indeed show the little window on my primary screen, but once fully launched is in borderless fullscreen window on the right monitor
(i think it only had a bug where because my primary monitor is id 1 and my 1st secondary monitor is id 0 and 2nd secondary monitor is id 2, when i use 2 it works as intended and show on the 2nd secondary monitor, when i use 1 it show on my primary monitor, but when i use 0 it use my primary monitor too cause the 0 is assumed to be "current" aka primary, ig it should have used -1 to mean default "current" primary, but otherwise it just work)

**Comment by Kira-NT** [comment]
> Can't you just create it on the primary monitor and move it to the right monitor after it's been created ?

Yep, I can, but it will still appear on the primary monitor first for a few seconds, which is annoying. Admittedly, this is less annoying than losing control over the mouse entirely, so that's a sacrifice I'm willing to make for now.

(Note: Previously, I tried to make the window invisible until the setup was finished to prevent it from jumping all over the user's monitors. However, a call to `glfwShowWindow` resets the window's position, which is the opposite of what I need. That's why I resorted to using the fullscreen startup method, which allows the window to appear on the chosen monitor immediately.)

**Comment by Kira-NT** [comment]
The fullscreen startup is gone. Just to check one last time that there are no more obvious issues I might have missed, here are the test builds again:

 - 1.19.3-1.19.4: https://github.com/Kir-Antipov/cubes-without-borders/actions/runs/9668602876
 - 1.20.x: https://github.com/Kir-Antipov/cubes-without-borders/actions/runs/9668611134
 - 1.21: https://github.com/Kir-Antipov/cubes-without-borders/actions/runs/9668619203

**Comment by Julienraptor01** [comment]
> The fullscreen startup is gone. Just to check one last time that there are no more obvious issues I might have missed, here are the test builds again:
> 
>     * 1.19.3-1.19.4: https://github.com/Kir-Antipov/cubes-without-borders/actions/runs/9668602876
> 
>     * 1.20.x: https://github.com/Kir-Antipov/cubes-without-borders/actions/runs/9668611134
> 
>     * 1.21: https://github.com/Kir-Antipov/cubes-without-borders/actions/runs/9668619203

lgtm

**Comment by Kira-NT** [comment]
Thanks to everyone involved for your perspective on the problem and for your assistance. Also, apologies for the inconvenience! The new version should be up on Modrinth and CurseForge in a few minutes.

**Comment by Julienraptor01** [comment]
> Thanks to everyone involved for your perspective on the problem and for your assistance. Also, apologies for the inconvenience! The new version should be up on Modrinth and CurseForge in a few minutes.

Thank you for dealing with it so fast ! ❤️

**Comment by mpustovoi** [comment]
> Thanks to everyone involved for your perspective on the problem and for your assistance. Also, apologies for the inconvenience! The new version should be up on Modrinth and CurseForge in a few minutes.

Thank you!
